sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://192.168.0.140:5432/ds0?useUnicode=true&characterEncoding=utf8
        username: postgres
        password: 123456

      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://192.168.0.148:5432/ds1?useUnicode=true&characterEncoding=utf8
        username: postgres
        password: 123456
    config:
      sharding:
        tables:
          t_order:
            key-generator-column-name: id
        props:
          sql:
            show: true
      masterslave:
        name: ds_ms
        master-data-source-name: ds0
        slave-data-source-names: ds0
        load-balance-algorithm-type: round_robin

